### ISSUE TITLE
I can't move or close the window

### ISSUE THREAD

**Issue by S-Kee** [maykbrito/electron-desktop-custom-notion-omni#6]
I can't move or close the window

**Comment by cleysonsilvame** [comment]
You can change this behavior by changing the `frame` to `true` in the` BrowserWindow` constructor _on line 22_ of 
[`app.js`](https://github.com/maykbrito/electron-desktop-custom-notion-omni/blob/main/app.js)

**Comment by S-Kee** [comment]
Thanks
